{{- if (($.Values.certManager).values) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-cert-manager-config
  namespace: {{ $.Release.Namespace }}
data:
  values: |
  {{- (tpl ($.Values.certManager.values | toYaml | toString) $) | nindent 4 }}
{{- end }}