apiVersion: v2
name: cert-manager-bundle
description: cert-manager Bundle with crossplane resources
home: https://github.com/giantswarm/cert-manager-bundle
icon: https://s.giantswarm.io/app-icons/cert-manager/1/light.svg
version: [[ .Version ]]
annotations:
  application.giantswarm.io/app-type: "bundle"
  application.giantswarm.io/in-cluster-app: "true"
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: shield
