---
apiVersion: v1
data:
  values: |
    global:
      connectivity:
        availabilityZoneUsageLimit: 3
        network: {}
        topology: {}
      controlPlane: {}
      metadata:
        name: example
        organization: giantswarm
      nodePools:
        nodepool0:
          instanceType: m5.large
          maxSize: 1
          minSize: 1
          rootVolumeSizeGB: 300
      providerSpecific: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: example
  name: example-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: example
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: example-userconfig
      namespace: org-giantswarm
  version: 0.72.0
---
apiVersion: v1
data:
  values: |
    clusterName: example
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: example
  name: example-default-apps-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: example
    giantswarm.io/managed-by: cluster
  name: example-default-apps
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: example-cluster-values
      namespace: org-giantswarm
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: example-default-apps-userconfig
      namespace: org-giantswarm
  version: 0.51.0
---
apiVersion: v1
data:
  values: |
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: example
  name: example-cert-manager-bundle-user-values
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: cert-manager-bundle
    giantswarm.io/cluster: example
  name: example-cert-manager-bundle
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  config:
    configMap:
      name: example-cluster-values
      namespace: org-giantswarm
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: example
    inCluster: true
    secret:
      name: example-kubeconfig
      namespace: org-giantswarm
  name: cert-manager-bundle
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: example-cert-manager-bundle-user-values
      namespace: org-giantswarm 
  version: 1.0.0
